baseURL = "https://www.sammajiva.be/"
languageCode = "nl-NL"
title = "Sammajiva"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # aantal posts op de postspagina
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = ""
  facebook = "https://www.facebook.com/sammajiva.coop/"
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/company/sammajiva"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-green"
  featured_image = "/images/rode-clover-zaailingen2.JPG"
  recent_posts_number = 0
